[[headers]]
for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-XSS-Protection = "1; mode=block"
  Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://images.unsplash.com https://images.pexels.com data:; connect-src 'self' https://script.google.com; object-src 'none'; frame-ancestors 'none';"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
for = "/assets/images/*"
  [headers.values]
  Cache-Control = "public, max-age=86400"

[[headers]]
for = "/assets/fonts/*"
  [headers.values]
  Cache-Control = "public, max-age=86400"

[[headers]]
for = "/assets/css/*"
  [headers.values]
  Cache-Control = "public, max-age=3600"

[[headers]]
for = "/assets/js/*"
  [headers.values]
  Cache-Control = "public, max-age=600"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 301

[[redirects]]
  from = "/account"
  to = "/account.html"
  status = 301
